export const CommandIds = {
  Open: 'jetbrains-commit-manager.open',
  OpenDiff: 'jetbrains-commit-manager.openDiff',
  OpenFile: 'jetbrains-commit-manager.openFile',
  CreateChangelist: 'jetbrains-commit-manager.createChangelist',
  DeleteChangelist: 'jetbrains-commit-manager.deleteChangelist',
  RenameChangelist: 'jetbrains-commit-manager.renameChangelist',
  CommitSelectedFiles: 'jetbrains-commit-manager.commitSelectedFiles',
  StashSelectedFiles: 'jetbrains-commit-manager.stashSelectedFiles',
  MoveFileToChangelist: 'jetbrains-commit-manager.moveFileToChangelist',
  ToggleFileSelection: 'jetbrains-commit-manager.toggleFileSelection',
  Refresh: 'jetbrains-commit-manager.refresh',
  CollapseAll: 'jetbrains-commit-manager.collapseAll',
  RevertSelectedFiles: 'jetbrains-commit-manager.revertSelectedFiles',
  RevertFile: 'jetbrains-commit-manager.revertFile',
  RevertChangelist: 'jetbrains-commit-manager.revertChangelist',
  SelectAllFiles: 'jetbrains-commit-manager.selectAllFiles',
  DeselectAllFiles: 'jetbrains-commit-manager.deselectAllFiles',
  CommitFromStatusBar: 'jetbrains-commit-manager.commitFromStatusBar',
  StashFromStatusBar: 'jetbrains-commit-manager.stashFromStatusBar',
  UpdateCommitMessage: 'jetbrains-commit-manager.updateCommitMessage',
  ToggleAutoStage: 'jetbrains-commit-manager.toggleAutoStage',
  NavigateDown: 'jetbrains-commit-manager.navigateDown',
  NavigateUp: 'jetbrains-commit-manager.navigateUp',
  ToggleCheckbox: 'jetbrains-commit-manager.toggleCheckbox',
  Test: 'jetbrains-commit-manager.test',
  ChangelistsFocus: 'jetbrains-commit-manager.changelists.focus',
  VscodeDiff: 'vscode.diff',
  VscodeOpen: 'vscode.open',
  ListFocusDown: 'list.focusDown',
  ListFocusUp: 'list.focusUp',
  ListSelect: 'list.select',
  SetContext: 'setContext',
} as const;

export type CommandIds = (typeof CommandIds)[keyof typeof CommandIds];
